{"name":"MongoNetworkError","level":"error","message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}] failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:311:20)\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:418:26)\n    at Socket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
{"name":"MongoNetworkError","level":"error","message":"failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}] failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:311:20)\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/home/rpurswell/my-node-apps/organizer/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:418:26)\n    at Socket.emit (events.js:311:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}
{"code":"ERR_IPC_CHANNEL_CLOSED","level":"error","message":"Channel closed Channel closed","stack":"Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed\n    at process.target.send (internal/child_process.js:679:16)\n    at reportSuccess (/home/rpurswell/my-node-apps/organizer/node_modules/jest-worker/build/workers/processChild.js:67:11)"}
{"code":"ERR_IPC_CHANNEL_CLOSED","level":"error","message":"Channel closed Channel closed","stack":"Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed\n    at process.target.send (internal/child_process.js:679:16)\n    at reportSuccess (/home/rpurswell/my-node-apps/organizer/node_modules/jest-worker/build/workers/processChild.js:67:11)"}
{"code":"ERR_IPC_CHANNEL_CLOSED","level":"error","message":"Channel closed Channel closed","stack":"Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed\n    at process.target.send (internal/child_process.js:679:16)\n    at reportSuccess (/home/rpurswell/my-node-apps/organizer/node_modules/jest-worker/build/workers/processChild.js:67:11)"}
{"code":"ERR_IPC_CHANNEL_CLOSED","level":"error","message":"Channel closed Channel closed","stack":"Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed\n    at process.target.send (internal/child_process.js:679:16)\n    at reportSuccess (/home/rpurswell/my-node-apps/organizer/node_modules/jest-worker/build/workers/processChild.js:67:11)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:22:41\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:22:41\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:22:41\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:36:40\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at /home/rpurswell/my-node-apps/organizer/middleware/validator.js:5:9\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:36:40\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at /home/rpurswell/my-node-apps/organizer/middleware/validator.js:5:9\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
{"level":"error","message":"req is not defined req is not defined","stack":"ReferenceError: req is not defined\n    at Function.lookup (/home/rpurswell/my-node-apps/organizer/models/habbitNote.js:14:53)\n    at /home/rpurswell/my-node-apps/organizer/routes/habbitNote.js:36:40\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at /home/rpurswell/my-node-apps/organizer/middleware/validator.js:5:9\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/validateObjectId.js:4:1)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/route.js:137:13)\n    at Object.<anonymous>.module.exports (/home/rpurswell/my-node-apps/organizer/middleware/auth.js:13:6)\n    at newFn (/home/rpurswell/my-node-apps/organizer/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/rpurswell/my-node-apps/organizer/node_modules/express/lib/router/layer.js:95:5)"}
